### ISSUE TITLE
Usage with React 16.

### ISSUE THREAD

**Issue by chandanky23** [estrattonbailey/relaze#3]
The lib doesn't seem to work with latest react beta. Fails with the following error, any plans to support it?

Related callemall/material-ui#7025

```
main.bundle.js:108293 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at inViewport (main.bundle.js:108293)
    at main.bundle.js:108388
    at main.bundle.js:119040
    at Object.update (main.bundle.js:119040)
    at Object.update (main.bundle.js:119040)
    at Relaze.init (main.bundle.js:108391)
    at Relaze.componentDidMount (main.bundle.js:108420)
    at commitLifeCycles (main.bundle.js:34509)
    at commitAllLifeCycles (main.bundle.js:35291)
    at HTMLUnknownElement.callCallback (main.bundle.js:24919)

```

**Comment by chandanky23** [comment]
> Regarding the error shared by me  - 
I found out that there is an issue with the import .. 
In the **index.js file under example folder ....** 

you are doing an import , i.e, 
`import` Lazy from 'relaze'`

which should be something like ...
`import Lazy from './package'`

Doing so the error which i shared above could be solved . 
**Let me know incase i figured something wrong.** 

Thanks .

**Comment by estrattonbailey** [comment]
Apologies, @chandanky23! Sorry, I didn't see this. Did you get it figured out? Were you just running the example?

The mistake in the example file is probably because I usually `npm link` packages as I'm developing them, and I must have forgotten to swap it back.

**Comment by estrattonbailey** [comment]
@chandanky23 just integrated this into a current project using 16.2.0 and works fine. Also updated the API in v2.0.0.

**Comment by chandanky23** [comment]
Works... Thank you
